on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create KinD Cluster
        run: |
          kind create cluster --config kind/cluster-config.yaml
          kubectl config current-context
          kubectl get nodes -o wide

      - name: Install Traefik as Ingress Controller
        run: |
          helm repo add traefik https://traefik.github.io/charts && helm repo update
          kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v3.4/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
          helm install traefik traefik/traefik
          kubectl wait --for=condition=ready pod \
            --selector=app.kubernetes.io/name=traefik \
            --timeout=120s
          kubectl get pods -l app.kubernetes.io/name=traefik

      - name: Deploy services
        run: |
          helm upgrade --install foo ./k8s/charts/echo-template -f ./k8s/deployment/foo/values.yaml
          helm upgrade --install bar ./k8s/charts/echo-template -f ./k8s/deployment/bar/values.yaml
          kubectl wait --for=condition=ready pod -l 'app in (foo,bar)' --timeout=120s
          kubectl get pods -l 'app in (foo,bar)'

      - name: Port‑forward Traefik and verify services
        run: |
          kubectl port-forward -n default svc/traefik 8080:80 &
          sleep 5
          curl -f -H "Host: foo.localhost" http://localhost:8080
          curl -f -H "Host: bar.localhost" http://localhost:8080

      - name: Install Locust
        run: |
          python3 -m pip install --upgrade pip
          pip install locust

      - name: Run Locust load test
        run: |
          locust -f ./load_test/locustfile.py --headless -u 100 -r 10 --host http://localhost:8080 --run-time 30s --csv=locust_report
          python summarize_locust.py

      - name: Post summary as PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: locust_summary.md





