on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create KinD Cluster
        run: |
          kind create cluster --config kind/cluster-config.yaml
          kubectl config current-context
          kubectl get nodes -o wide

      - name: Deploy services
        run: |
          helm upgrade --install foo ./k8s/charts/echo-template -f deployment/foo/values.yaml

